### ISSUE TITLE
rust

### ISSUE THREAD

**Issue by gilescope** [sirbrillig/grepdef#23]
Be cool to add rust as a lang as for big projects grep is way faster than anything else.

**Comment by sirbrillig** [comment]
Definitely. That's why the default engine for grepdef is ripgrep, which is written in Rust!

I think this would be a great addition, but I'm not confident in my Rust knowledge to add it myself right now. We'd need someone who can come up with a regexp. I'm open to PRs!

**Comment by sirbrillig** [comment]
Fixed by https://github.com/sirbrillig/grepdef/pull/33
