### ISSUE TITLE
Error: Unable to install the latest version

### ISSUE THREAD

**Issue by spraveenitpro** [sirbrillig/grepdef#35]
### Installation failure:

```
/var/folders/kv/m13155mx5896bt_ntbg6qwy80000gn/T/cargo-installaRoHJZ  cargo install grepdef                                                                                                ok  04:39:31 pm
    Updating crates.io index
  Installing grepdef v3.1.0
error: failed to compile `grepdef v3.1.0`, intermediate artifacts can be found at `/var/folders/kv/m13155mx5896bt_ntbg6qwy80000gn/T/cargo-installBSjQL6`

Caused by:
  failed to select a version for the requirement `clap = "^4.5.9"`
  candidate versions found which didn't match: 3.2.25, 3.2.24, 3.2.23, ...
  location searched: crates.io index
  required by package `grepdef v3.1.0`
```

Looks like it is expecting **clap = "^4.5.9"** . Trying to build results in:

![](https://d.pr/i/xhQgBB+)
Link to screenshot (https://d.pr/i/xhQgBB )

**Comment by sirbrillig** [comment]
That's bad! Thanks for the ping. Some quick google searching suggests that this might happen if your local version of Rust is out-of-date. Could you try running `rustup update` and then `cargo install grepdef` again?

clap 4.5.9 [definitely exists](https://crates.io/crates/clap/4.5.9) and it's interesting that your command only found versions up to 3.2.25. This makes me think it's a caching issue.

**Comment by spraveenitpro** [comment]
That was it! Looks like I had a older Rust what was fixed with `rustup update` then `cargo install grepdef`. 

![](https://d.pr/i/6nB2Fu+)
Link to screenshot (https://d.pr/i/6nB2Fu )

Very useful for my current project :) 


Great work!
